selendroid-client/pom.xml
selendroid-client/src/main/java/io/selendroid/client/SelendroidDriver.java
selendroid-server-common/src/main/java/io/selendroid/server/common/utils/CallLogEntry.java
selendroid-server/pom.xml
selendroid-server/src/main/java/io/selendroid/server/handler/AddCallLog.java
selendroid-server/src/main/java/io/selendroid/server/handler/ReadCallLog.java

* Replaced with JSONObject and JSONArray custom parsing

Removed Gson dependency from server and client

---

selendroid-common/src/main/java/io/selendroid/common/device/DeviceTargetPlatform.java
selendroid-common/src/test/java/io/selendroid/common/device/DeviceTargetPlatformTest.java

Added support for Android 20 and 21 as well as tests to confirm that the max support version is Android 21.

Added support for Android 20 and 21

---

android-driver/pom.xml
pom.xml
selendroid-server/pom.xml
selendroid-test-app/pom.xml

I needed to update to the latest android maven plugin.

Fixing maven issues.

---

selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
selendroid-standalone/src/main/java/io/selendroid/standalone/server/handler/NetworkConnectionHandler.java

...nections activity. Using the default back button to get back to the app under test.

setAirplaneMode(true) for Android API 21

---

pom.xml
selendroid-common/pom.xml

@lukeis please review, merge and delete branch

Using latest selenium release.

---

selendroid-standalone/src/main/java/io/selendroid/standalone/builder/SelendroidServerBuilder.java

@lukeis 
updated getJarVersionNumber() based on lukes comments

gets app version from pom.xml if class path doesn't start with jar

---

selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java

Added apiTargetType info on wd/hub/status page in selendroid-standalone

Added display of ApiTargetType on wd/hub/status page in selendroid-standalone

---

selendroid-server/src/main/java/io/selendroid/server/action/ActionChain.java
selendroid-server/src/main/java/io/selendroid/server/action/ActionChains.java
selendroid-server/src/main/java/io/selendroid/server/handler/Actions.java
selendroid-server/src/test/java/io/selendroid/server/ActionChainTest.java

Worked in collaboration with @chooper9 @colindmurray 
Refactored SafeHandle for future multitouch implementation.
Previous implementation didn't properly handle thread sleep for synchronizing touch events.

Action chain

---

selendroid-server/src/main/java/io/selendroid/server/action/ActionChain.java
selendroid-server/src/main/java/io/selendroid/server/action/ActionContext.java
selendroid-server/src/main/java/io/selendroid/server/action/touch/PointerCancel.java
selendroid-server/src/main/java/io/selendroid/server/action/touch/PointerDown.java
selendroid-server/src/main/java/io/selendroid/server/action/touch/PointerMove.java
selendroid-server/src/main/java/io/selendroid/server/action/touch/PointerUp.java
selendroid-server/src/main/java/io/selendroid/server/android/AndroidTouchScreen.java
selendroid-server/src/main/java/io/selendroid/server/handler/Actions.java
selendroid-server/src/main/java/io/selendroid/server/model/TouchScreen.java
selendroid-server/src/test/java/io/selendroid/server/ActionChainTest.java

Worked in collaboration with @colindmurray.
Implemented multitouch functionality usable from creating a MultitouchAction with multiple TouchActions.

Multitouch

---

selendroid-common/src/main/java/io/selendroid/common/device/DeviceTargetPlatform.java
selendroid-common/src/test/java/io/selendroid/common/device/DeviceTargetPlatformTest.java

Test Plan: Ran tests on Android 22. Tests failed. Updated jars experimentally. Ran tests. Tests passed.

Added support for Android 22 and modified max value test

---

selendroid-common/src/main/java/io/selendroid/common/SelendroidCapabilities.java
selendroid-common/src/test/java/io/selendroid/common/SelendroidCapabilitiesTest.java

Address #892: allow "false" or "true" as String value for boolean capabilities…
I have signed the CLA.

Allow string value for boolean capabilities

---

selendroid-server/src/main/java/io/selendroid/server/model/SelendroidWebDriver.java

Need to wrap the cordova clients as well.
My test app also likes to do "special" things to the cordova webview class.
The WebView's class name is that of a nested class and doesn't return anything for getSimpleName,
so need to rely on getting a ClassCast exception to determine if it really is cordova or not.

wat the wrap.

---

selendroid-server/src/main/java/io/selendroid/server/model/AndroidNativeElement.java

This is needed especially if checking for attributes on a WebView
(in particular wanting to check WebView.getScale() )
@asm89

may need to run on UI thread to get attribute

---

selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java

This pull request is a workaround for issue #588.
#588 is closed but still exists on latest release 0.16.0 and master HEAD.
I reproduced #588 in the following condition:
1. launch Android 4.1.2, *selendroid build target version*, ARM emulator,
note: there are no orphaned process with launching Intel Atom emulator with same version.
2. start selendroid with `java -jar selendroid-standalone-0.16.0-with-dependencies.jar`
3. running the client test code
4. count orphaned processes with `adb shell ps | grep -c io.selendroid.androiddriver`
client test code to reproduce:
```
DesiredCapabilities desiredCapabilities = SelendroidCapabilities.android();
URL hubUrl = null;
try {
hubUrl = new URL("http://localhost:4444/wd/hub");
} catch (MalformedURLException ignored) { }
RemoteWebDriver driver = new …
```

kill orphaned processes after test has finished

---

.gitignore
.travis.yml
android-driver/build.gradle
build.gradle
gradle.properties
selendroid-client/build.gradle
selendroid-common/build.gradle
selendroid-grid-plugin/build.gradle
selendroid-server-common/build.gradle
selendroid-server/build.gradle
selendroid-standalone/build.gradle
selendroid-standalone/src/test/java/io/selendroid/standalone/android/impl/AbstractDeviceTest.java
selendroid-standalone/src/test/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulatorTests.java
selendroid-standalone/src/test/java/io/selendroid/standalone/android/impl/DefaultHardwareDeviceTests.java
selendroid-standalone/src/test/java/io/selendroid/standalone/server/e2e/SessionCreationE2ETests.java
selendroid-test-app/build.gradle
settings.gradle

**Changes**
1. Add root build gradle file along-with sub-projects gradle files.
2. Ignore 5 test.
3. Modify syntax for two test case.
**Build Command**
1. gradle clean build

Gradle build system

---

selendroid-server/src/main/java/io/selendroid/server/InstrumentationArguments.java
selendroid-server/src/main/java/io/selendroid/server/LightweightInstrumentation.java
selendroid-server/src/main/java/io/selendroid/server/ServerInstrumentation.java
selendroid-server/src/main/java/io/selendroid/server/util/Intents.java

Allow Selendroid to start services in the background instead of always launching an Activity. Useful to test cases where the UI doesn't show up immediately.
/cc @asm89

Add support for starting services

---

build.gradle

Might be useful for other types of scripts

Add Gradle task for printing current version

---

selendroid-common/src/main/java/io/selendroid/common/SelendroidCapabilities.java
selendroid-server-common/src/main/java/io/selendroid/server/common/utils/SelendroidArguments.java
selendroid-server/src/main/java/io/selendroid/server/DefaultServerInstrumentation.java
selendroid-server/src/main/java/io/selendroid/server/InstrumentationArguments.java
selendroid-server/src/main/java/io/selendroid/server/ServerInstrumentation.java
selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java

This PR adds the ability to pass arguments to the Application Under Test via instrumentation arguments. This is done by adding a JSONObject to the required capabilities, these are then sent to the AUT via instrumentation arguments, where they can be read as strings. This only supports flat objects

Pass arbitrary arguments to AUT via instr args

---

selendroid-common/src/main/java/io/selendroid/common/SelendroidCapabilities.java

Fix getExtraAUTArg to support non String values

---

selendroid-server/src/main/java/io/selendroid/server/DefaultServerInstrumentation.java
selendroid-server/src/main/java/io/selendroid/server/JUnitRunnerServerInstrumentation.java
selendroid-server/src/main/java/io/selendroid/server/SelendroidInstrumentation.java

This PR does some refactoring of DefaultServerInstrumentation and JUnitRunnerInstrumentation to reduce redundancies and adds some log statements for the instrumentation's lifecycle

Add logging for instrumentation lifecycle methods

---

selendroid-common/src/main/java/io/selendroid/common/device/DeviceTargetPlatform.java
selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java

This also addresses the code in PR #1063 and #1110

Adding newer android SDK versions to DeviceTargetPlatform.java

---

.travis.yml

Use the correct preinstalled component from the list here: https://docs.travis-ci.com/user/languages/android/#Pre-installed-components

Use the correct system image for android-16

---

selendroid-server/src/main/java/io/selendroid/server/model/AndroidNativeElement.java

In some cases this is still necessary

Preserve original click behavior

---

selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidConfiguration.java
selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidLauncher.java
selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidSdk.java

This PR adds the ability to specify custom adb installations in `SelendroidConfiguration`

Add support for using custom adb installation
