selendroid/selendroid

- selendroid-common/src/test/java/io/selendroid/common/SelendroidCapabilitiesTest.java
- selendroid-server-common/src/main/java/io/selendroid/server/common/SelendroidResponse.java
- selendroid-server-common/src/test/java/io/selendroid/server/common/SelendroidResponseTest.java
- selendroid-server/src/main/java/io/selendroid/server/handler/SafeRequestHandler.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
We not only return Selendroid stack traces to clients in case of an `UNKNOWN_ERROR`. The reason is documented in `SelendroidResponse`:
```
// Also include the Selendroid stack trace. Only do this in case of unknown errors for easier debugging.
// In case of an expected error the stack trace is unnecessary and users often find it confusing.
```
The error message returned to client is:
Before:
- status code: `SESSION_NOT_CREATED_EXCEPTION`
- message:
```
io.selendroid.server.common.exceptions.SelendroidException: Error occurred while starting selendroid-server on the device
at io.selendroid.standalone.android.impl.AbstractDevice.startSelendroid(AbstractDevice.java:267)
at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:264 …
```
> Cleaner exception when instrumentation fails

- selendroid-common/src/main/java/io/selendroid/common/SelendroidCapabilities.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidEmulator.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulator.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultHardwareDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/DeviceStore.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulatorTests.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/server/model/DeviceStoreFixture.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/server/model/DeviceStoreTest.java
So users can select a specific device together with the SDK version
for their tests. Previously, users can only specify the SDK version
for the tests and if there are several devices with the same SDK
version, selendroid will automatically select the first device to
carry out the test, which may not be the intended device for the
test.
This parameter can be ignored if the users are not desired to select
a specific device for the test.
Signed-off-by: Binh Vu <bvu@paypal.com>
> Adding "deviceType" as a configurable parameter option.

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
We log an uninteresting exception every two seconds when waiting for the Selendroid server to come up on the device. This makes the log harder to read:
```
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:196)
at java.net.SocketInputStream.read(SocketInputStream.java:122)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
at …
```
> Don't log exception when waiting for the Selendroid server to start

- selendroid-server/src/main/java/io/selendroid/server/model/internal/AbstractNativeElementContext.java
- selendroid-server/src/test/java/io/selendroid/server/model/internal/AbstractNativeElementContextTest.java
The current implementation of `AbstractNativeElementContext#searchViews`
can end up looking at multiple top level views. Selendroid makes sure
that the top level views passed to the `searchViews()` method are
ordered by when they were last painted on the screen. Searching for
views is then done by a breadth-first search to return elements higher
up in the view hierarchy first.
Given the two top level views below, the previous version of the
`searchViews()` method would return the following nodes in the order:
`[I, D, F, J, L]`.
```
a                     g
/     \              /     \
b       c             h       I (1)
/     \     \         /     \     \
D(2)    e     F (3)    J(4)   k     L (5)
```
*Capital letters are matching nodes.*
After this patch the method will return: `[D, F, I, …
> Fix native view search with multiple top level views

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultDeviceManager.java
As I've noticed in my testNG suite which uses Selendroid standalone, the commit f735a8a breaks the test execution of more than 1 test in a suite. With this change it works again.
The need for the original change was due to some orphaned processes upon test termination. This has to be addressed separately (and shouldn't break any already present functionality).
Also:
Simplified the logic of iterating through devices in DefaultDeviceManager#initializeAdbConnection()
> Reverted the 'adb.terminate()' call (back into if condition). 

- selendroid-server/src/main/java/io/selendroid/server/model/AndroidNativeElement.java
This gives us more information about what is happening on the device when elements are clicked.
> Log click position

- selendroid-standalone/src/main/java/io/selendroid/standalone/server/grid/SelfRegisteringRemote.java
The SelendroidCapabilities requires the selendroid grid node to have the capability: platformName => android
> fix registration of selendroid server into a selenium grid

- selendroid-server/src/main/java/io/selendroid/server/model/DefaultSelendroidDriver.java
While testing a native app calling switchTo().defaultContent() on the Driver results in a NullPointerException.
This minor bug is fixed by this commit.
> fix NPE on native apps driver.switchTo().defaultContent()

- selendroid-server/src/main/java/io/selendroid/server/model/AndroidNativeElementFactory.java
- selendroid-server/src/main/java/io/selendroid/server/model/ClassPredicate.java
- selendroid-server/src/main/java/io/selendroid/server/model/ContentDescriptionPredicate.java
- selendroid-server/src/main/java/io/selendroid/server/model/DefaultAndroidNativeElementFactory.java
- selendroid-server/src/main/java/io/selendroid/server/model/Factories.java
- selendroid-server/src/main/java/io/selendroid/server/model/IdPredicate.java
- selendroid-server/src/main/java/io/selendroid/server/model/PartialTextPredicate.java
- selendroid-server/src/main/java/io/selendroid/server/model/PredicatesFactory.java
- selendroid-server/src/main/java/io/selendroid/server/model/TagNamePredicate.java
- selendroid-server/src/main/java/io/selendroid/server/model/TextPredicate.java
- selendroid-server/src/main/java/io/selendroid/server/model/internal/AbstractNativeElementContext.java
- selendroid-server/src/main/java/io/selendroid/server/model/internal/execute_native/FindElementByAndroidTag.java
- selendroid-server/src/test/java/io/selendroid/server/model/KnownElementsTest.java
Summary:
Custom android views sometimes require specific behaviours.
This diff introduce factories for predicates and android elements, allowing test
developers to extend them in order to setup specific behaviours at bootstrap.
Test Plan: Ran with custom views and checked using custom factories worked.
Differential Revision: https://reviews.facebook.net/D33639
> Introduce Predicate and AndroidElement factories

- selendroid-server/assets/inspector/inspector.js
- selendroid-server/pom.xml
The `assets` directory contains all the JS and CSS files for the Selendroid inspector. The directory was missing in the APK since https://github.com/selendroid/selendroid/commit/7ae21137dde0b17522f08db20fb248ac0c3a9aa0.
This fixes the missing assets. 
The Selendroid inspector still crashes in JS in `onTreeLoaded`:
this.root = this.jstree.jstree('get_json')[0];
this.xml = this.root.metadata.xml;  // this.root is a div, metadata is undefined
I added at least some try-catch-finally error handling (this was missing) but I'm not familiar with the Inspector JS code. @DominikDary can you explain the purpose of `this.root.metadata.xml`? I don't see any recent changes to `inspector.js` or jQuery version bumps that could break this.
> Add assets for inspector

- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
Due to various conditions (race, user interaction between test runs, etc) the app isn't always in a clean state on launch with noClearData=false. Adding a data clear before the app is launched.
> Clear data before app launch

- selendroid-client/src/main/java/io/selendroid/client/SelendroidDriver.java
as RemoteWebDriver implements and will always implement those two.
Drop overriding of the getScreenshotAs() method as it is functionally
equivalent to the one in the parent class. (Note, this change is
independent from the one dropping 'implements' declarations).
This is a no-op, fully backwards compatible change and it will
simplify things for Selenium project in the future.
> Drop explicit 'implements TakesScreenshot, JavascriptExecutor' declarations

- README.md
- selendroid-server/src/main/java/io/selendroid/server/model/AndroidWebElement.java
- selendroid-test-app/src/test/java/io/selendroid/support/BaseAndroidTest.java
- selendroid-test-app/src/test/java/io/selendroid/webviewdrivertests/WebElementInteractionTest.java
- third-party/cordova-3.7.0/mvnInstall.sh
When using native keyboard to send keys, then DOM event of type 'input' is triggered automatically by platform.
Opposite for AndroidWebElement, when setting value for INPUT element, then no DOM event of type 'input' is triggered.
This fix will trigger DOM event type 'input' after setting value of web element 'INPUT'.
AndroidWebElement is activated when Selenium session request has property nativeEvents set to false.
> Trigger DOM event of type 'INPUT' after changing value of INPUT element

- selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidConfiguration.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/SelendroidStandaloneServer.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/grid/SelfRegisteringRemote.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/server/grid/SelfRegisteringRemoteTest.java
If a grid hub was restarted, then SelendroidStandaloneServer will re-register itself again.
Commit details:
a task created for self registration - first check grid if the node already registered, and re-register if not.
then the task is scheduled for execution (recurrence is configured via -registerCycle argument) 
A nice feature that I found useful when having a farm of selendroid-servers. :-)
> Grid auto re-register

- selendroid-server/src/main/java/io/selendroid/server/handler/timeouts/TimeoutsHandler.java
- selendroid-server/src/main/java/io/selendroid/server/model/DefaultSelendroidDriver.java
- selendroid-server/src/main/java/io/selendroid/server/model/SelendroidDriver.java
- selendroid-server/src/main/java/io/selendroid/server/model/SelendroidWebDriver.java
Implemented #300 
Allows to edit the page load timeout through driver.manage().timeouts().PageLoadTimeout(long seconds, java.util.concurrent.TimeUnit unit)
Will throw a TimeoutException if the page load exceeds the timeout.
> implemented driver.manage().timeouts().PageLoadTimeout()

- selendroid-server/src/main/java/io/selendroid/server/inspector/TreeUtil.java
- selendroid-server/src/main/java/io/selendroid/server/model/AndroidNativeElement.java
- selendroid-server/src/main/java/io/selendroid/server/model/internal/JsonXmlUtil.java
Currently its not possible to get details about errors with selendroid. this change just appends the error text to the page source.
> append error details to page source

- selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidConfiguration.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/builder/SelendroidServerBuilder.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
Added a command line flag, -deleteTmpFiles, to delete temporary files that persist in the temp directory. Files were being created after Selendroid Standalone Server was started and test app was run. When server is started with flag, then files will be deleted when server is stopped.
> Delete temporary created by Selendroid Server

- selendroid-common/src/main/java/io/selendroid/common/SelendroidCapabilities.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulator.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultHardwareDevice.java
Be more forgiving with Boolean desiredCapabilities in the case where the user sends the boolean value over as a String like "true" instead of true.
> User sends "true" for a Boolean DesiredCapability

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidEmulator.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulator.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultHardwareDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
On Android devices, if the screen is off, tests would not run; this turns the device on before running tests.  
#752   
@mtimkovich and I worked on this.  
Should I squash the commits?
> Wake screen before running tests

- selendroid-server/src/main/java/io/selendroid/server/model/internal/AbstractNativeElementContext.java
Commit 4afa5ccedc53b0b73319dfe3a6917db0f557fddc introduced the
AndroidNativeElementFactory abstraction, but forgot to update this call
site.
> Use AndroidNativeElementFactory to create native element

- selendroid-server/src/main/java/io/selendroid/server/android/ViewHierarchyAnalyzer.java
- selendroid-server/src/main/java/io/selendroid/server/model/DecorViewPredicate.java
- selendroid-server/src/main/java/io/selendroid/server/model/PredicatesFactory.java
Simply moved DecorViewPredicate into its own file and adds it to the PredicateFactory.
Test plan:
mvn clean compile package
> Move DecorViewPredicate to own class and add to PredicateFactory

- selendroid-server/src/main/java/io/selendroid/server/android/AndroidWait.java
The w3c webdriver spec states that the implicit wait timeout should be
zero milliseconds unless stated otherwise:
> A session has an associated session implicit wait timeout that
> specifies a time to wait for the implicit element location strategy
> when locating elements using find element and find elements. Unless
> stated otherwise it is zero milliseconds.
- https://w3c.github.io/webdriver/webdriver-spec.html
Selendroid had an implicit wait timeout of 5 seconds. The timeout leads
to unexpected behavior in the case of elements that are not present in
the view hierarchy. If a test wants to assert that an element is not
present in the current view it will always take 5 seconds to get a
response.
The old behavior can be re-enabled by calling:
```
driver
.manage()
.timeouts() …
```
> Default implicit wait time should be 0 as per spec

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulator.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/builder/SelendroidServerBuilder.java
- Add WXGA720 skin for detection of screen resolution.
- Optimize screenshots from standalone server - use 3 bytes per pixel instead of 4 bytes. Produces 25% smaller BufferedImage object.
- Fix bug SelendroidServerBuilder when executing tests and using default keystore alias and passwords and androidKeyStore file exists - initialize fields with default values.
> Various fixes

- selendroid-client/src/main/java/io/selendroid/client/SelendroidDriver.java
AddCallLogTest was broken. Turns out the `readCallLog()` method was
actually broken. The `execute()` method returns an `ArrayList<String>`,
so the cast to `String` was erroring.
Changed the cast to the appriopriate one and fixed the loop that parses
the individual call log entries. Added extra error handling for the
class cast exception.
> [client] Fix SelendroidDriver#readCallLog()

- selendroid-test-app/src/test/java/io/selendroid/support/BaseAndroidTest.java
When debugging what's going on with tests it's very useful to have the
debug output of the selendroid server on the emulator.
> [test-app] Set log level to DEBUG for tests

- selendroid-test-app/src/test/java/io/selendroid/nativetests/WaitForProgressBarGoneAwayTest.java
Disabling three tests that fail from time to time. The tests themselves
seem to be okish, but sometimes they fail with a
StaleElementReferenceException. Not sure why, disabling the tests for
now.
> [test-app] Unbreak WaitForProgressBarGoneAwayTest

- selendroid-test-app/src/test/java/io/selendroid/nativetests/SendKeyAndNativeKeyTest.java
The test will sometimes pass, but most of the times it will enter a
weird black screen with no search results. It seems to be because the
input manager is rejecting input events from time to time.
> [test-app] Unbreak SendKeyAndNativeKeyTest

- selendroid-test-app/src/test/java/io/selendroid/nativetests/NativeElementInteractionTest.java
Disabling one test that is flaky. The test itself is fine in theory, but
sometimes it's sending the click while the app is still animating
opening the registration screen. In this case the click is in the wrong
place and the select box does not get toggled.
> [test-app] Unbreak NativeElementInteractionTest

- selendroid-test-app/src/test/java/io/selendroid/nativetests/NativeElementFindingTest.java
Most "broken" tests weren't updated for UI changes in the app. Either
asserting the incorrect amount of elements, or wrong text string. I
fixed those cases.
The `shouldNotFindElementByIdFromPreviousActivity()` test not broken,
but exposes a bug in selendroid where selendroid will look for elements
in multiple top level views. The bug is is tracked in
https://github.com/selendroid/selendroid/issues/800. I am disabling the
test until the issue is fixed.
> [test-app] Unbreak NativeElementFindingTest

- selendroid-server/src/main/java/io/selendroid/server/model/ClassPredicate.java
- selendroid-test-app/src/test/java/io/selendroid/nativetests/NativeChildElementFindingTest.java
While looking into the failures of `NativeChildElementFindingTest` I
found out that the `ClassPredicate` is throwing an exception in case the
class is not found in the app. This regressed in
4afa5ccedc53b0b73319dfe3a6917db0f557fddc when the class predicate was
extracted to its own class.
I changed the class predicate to return false if the class is not found,
but logging a warning for discoverability. I changed the tests to use an
existing class in the normal case and added new tests to guard for the
appropriate behavior if the class does not exist.
> [server] Fix ClassPredicate

- selendroid-test-app/src/test/java/io/selendroid/nativetests/BackgroundAppTest.java
The test looks for the lines containing "mCurrentFocus" or "mFocusedApp"
in the output of an adb command to figure out which app is currently in
the foreground. Piping the ouput of the command through grep isn't
reliable. On my laptopt it yields an sh error. Moved the line filtering
to plain java instead.
> [test-app] Fix BackgroundAppTest

- selendroid-test-app/src/test/java/io/selendroid/driver/MultipleWebviewHandlingTests.java
The test previously hardcoded the port 8080. This works when you run a
test in isolation, because the odds of getting that port on the device
are pretty high. If multiple tests are run after each other the driver
will end up handing out higher ports. For now I fixed it by changing the
port to the port of the selendroid standalone driver that is used in all
these tests (4444). This works because the selendroid standalone driver
will forward requests to unknown paths to the device by default.
> [test-app] Unbreak MultipleWebviewHandlingTests

- selendroid-test-app/pom.xml
The test-app tests are still disabled by default. It occured to me that
not all tests were running. Removing the `executions` part of the
`pom.xml` file made the `includes` part of the surefire configuration
work.
> [test-app] Simplify surefire test configuration

- selendroid-test-app/src/test/java/io/selendroid/extension/ExtensionLoadTest.java
- selendroid-test-app/src/test/java/io/selendroid/support/BaseAndroidTest.java
`BaseAndroidTest` exposes a way to override the capabalities used to
start the selendroid server. Use that to only load the extensions in the
`ExtensionLoadTest`. Other tests don't rely on extensions, so it's
better if they don't load any.
The ExtensionLoadTest itself is broken. So I'm disabling it.
> [test-app] Only load extension in ExtensionLoadTest

- selendroid-standalone/src/main/java/io/selendroid/standalone/server/handler/GetLogTypes.java
Summary: The constructor of `JSONArray` that takes a string assumes that
the string is a JSON document. In the handler we want to construct a new
JSONArray to serialize it.
Test Plan:
Start selendroid-standalone and curl the `.../log/types` endpoint.
```
$ java -jar selendroid-standalone/target/selendroid-standalone-0.16.0-SNAPSHOT-with-dependencies.jar
$ $ curl -v localhost:4444/wd/hub/session/id/log/types
...
{"status":0,"sessionId":"id","value":["logcat"]}
```
> [standalone] Fix GetLogTypes handler

- selendroid-server/src/main/java/io/selendroid/server/android/ViewHierarchyAnalyzer.java
Summary: Previously selendroid would always try to look up the name of
the resource belonging to the id of the view. In some cases the view
value would actually be `View.NO_ID`. When trying to get the resource
name for `View.NO_ID` android will log a line like tho following to
logcat:
```
W/ResourceType(25943): No known package when getting name for resource number 0xffffffff
```
This change adds a check for `View.NO_ID`, making selendroid spam a lot
less.
Test Plan: Ran our internal e2e tests against selendroid with this
patch.
> [server] Do not try to get the resource name if the view has no id

- selendroid-server/src/main/java/io/selendroid/server/model/DefaultSelendroidDriver.java
- selendroid-server/src/main/java/io/selendroid/server/model/internal/AbstractNativeElementContext.java
- selendroid-server/src/test/java/io/selendroid/server/model/internal/AbstractNativeElementContextTest.java
Summary: In some cases selendroid ended up looking for elements in
multiple top level views. This resulted in cases where we would look up
an element by id, but the element was present in in a top level view
that was not a child of the current root view. The server happily
returns the element, but as soon as you try to interact with the
element, the known elements cache will check if the element is part of
the root level view and if that's not the case throw a
`StaleElementReference` without further information.
Instead of this confusing behavior, selendroid should search only in the
current top level view.
Test Plan:
- Ran our internal e2e tests against selendroid with this patch.
- unit tests
> [server] Do not search in multiple top level views

- selendroid-server/src/main/java/io/selendroid/server/android/ViewHierarchyAnalyzer.java
Summary: We are seeing cases where we're querying native elements, but
there is no current activity. Previously this would result in a
`NullPointerException` in the `ViewHierarchyAnalyzer`. This changes
fixes the exception and adds a fallback when looking for resources:
- added a check to see if the activity is `null`
- if that's the case, try to get the resources from the passed view
- before getting trying to get the resource name, check if the resources
returned are non null (we've seen that case as well)
Test Plan: Ran our internal e2e tests against selendroid with this
patch.
> [server] Fix NPE in ViewHierarchyAnalyzer

- selendroid-standalone/src/main/java/io/selendroid/standalone/server/handler/ProxyToDeviceHandler.java
Summary: Before this fix the selendroid standalone server would proxy
any command to the server on the device. The server on the device would
return `404 Not Found`. The standalone server then failed to deserialize
that string as JSON and actually ended up retrying proxying the command
to the device three times.
Test Plan: Create a new session and try to query existing and
non-existing endpoints:
```
$ curl localhost:4444/wd/hub/session/8fbdf5e5-bc39-7012-09f8-0417acdf6916/foo
{"status":0,"sessionId":"8fbdf5e5-bc39-7012-09f8-0417acdf6916","value":"UNKNOWN_COMMAND"}
$ curl localhost:4444/wd/hub/session/8fbdf5e5-bc39-7012-09f8-0417acdf6916/
{"status":0,"sessionId":"8fbdf5e5-bc39-7012-09f8-0417acdf6916",...}
$ curl -XPOST localhost:4444/wd/hub/session/8fbdf5e5-bc39-7012-09f8-0417acdf6916/log …
```
> [standalone] Fix HTTP response for unknown commands

- pom.xml
- selendroid-server/src/main/java/io/selendroid/server/model/SelendroidWebDriver.java
- selendroid-test-app/res/layout/webview.xml
- selendroid-test-app/src/main/java/io/selendroid/testapp/WebViewActivity.java
- selendroid-test-app/src/test/java/io/selendroid/webviewdrivertests/WebElementInteractionTest.java
If the AUT is setting their own custom WebViewClient or WebChromeClient, we need to wrap it and call the AUT's object instead of overriding it.
See commit message and code comments for more info.
> WebView needs to proxy WebViewClient & WebChromeClient

- selendroid-standalone/src/main/java/io/selendroid/standalone/server/grid/SelfRegisteringRemote.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
This pull request adds capabilities, such as `serial`, `model`, `platformVersion` for grid auto-register with collecting device config.
> add more node capability for grid auto-register

- selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidConfiguration.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/grid/SelfRegisteringRemote.java
This pull request adds [selenium grid node options]( https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/NodeOptions.json) support to selendroid grid auto-register.
These help to improve the selendroid scaling and high availability.
The default option value for these options are configured to fit selenium-server default ones with exception of `browserTimeout`.
I put the default `browserTimeout` value should be equal to `sessionTimeoutSeconds`, its default value is 30min.
> add more node options for grid auto-register

- selendroid-standalone/src/main/java/io/selendroid/standalone/builder/SelendroidServerBuilder.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/builder/SelendroidServerBuilderTest.java
Multiple selendroid standalone servers running on the same machine
could race for the previously predictable temp file locations.
> [standalone] Create proper tmp files / dirs

- selendroid-server-common/src/main/java/io/selendroid/server/common/http/HttpServer.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidLauncher.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/SelendroidStandaloneServer.java
There are cases where you don't care about the port selendroid
standalone starts on, as long as you can get the port after it started.
This commit changes the webserver start method to block until the netty
channel has opened and the netty thread returned the actual port the
server has started on.
Starting the standalone server on a random port can be achieved by using
0 as the configured port.
> Add option to start selendroid standalone on a random port

- selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidConfiguration.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
For some reason the standalone server will assign a new selendroid
server port to the client each time a new session is created. Made this
behavior configurable and default to whatever the behavior was before.
> Add option to re-use configured server port

- android-driver/build.gradle
- build.gradle
- jacoco.gradle
- properties.gradle
- selendroid-server/build.gradle
- selendroid-test-app/build.gradle
This commit would enable us to publish the release artifacts to jcenter using the command 
`gradle -PbintrayUser=<username> -PbintrayKey=<key> clean bintrayUpload`.
( where `<username>` and `<key>` are bintray account's username and API key).
Also, the published artifacts can be automatically synced to maven central repository by using OSS credentials under `bintray` task of gradle script.
> Publish selendroid release artifacts to jcenter

- selendroid-server/src/main/java/io/selendroid/server/InstrumentationArguments.java
- selendroid-server/src/main/java/io/selendroid/server/LightweightInstrumentation.java
- selendroid-server/src/main/java/io/selendroid/server/ServerInstrumentation.java
- selendroid-server/src/main/java/io/selendroid/server/util/Intents.java
Sometimes a test may want to launch an Activity via URI (e.g. to encode
a user ID or other information). This adds an "intent_uri" option to
both lightweight and regular server instrumentation that acts as a
fallback in case the main activity name is not specified.
/cc @asm89
> Add support for launching implicit intents

- selendroid-server/build.gradle
CI build is breaking because it's unable to instrument `selendroid-server/build/intermediates/classes/debug/io/selendroid/server/model/js/AndroidAtoms.class `. This PR removes Jacoco form the selendroid-server module to prevent this
> Remove Jacoco from selendroid-server

- selendroid-standalone/build.gradle
The jar task for selendroid-standalone builds a fat jar by default. This PR adds a separate task for creating a jar without any of the dependencies embedded
> Add Gradle task for building selendroid-standalone jar without deps

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
Combining multiple arguments was never officially supported by `adb`, it may not be supported by some devices and, on Nougat, it always fails. Simply separate the `r` and `d` arguments
> Fix install command for Nougat

- selendroid-server/src/main/java/io/selendroid/server/android/ViewHierarchyAnalyzer.java
There are cases where the mViews field in window manager is not set when we're analyzing the view hierarchy. This can cause a lot of noise in logs. This PR validates that and returns an empty set
> Add null check for accessing WindowManager views

- selendroid-common/src/main/java/io/selendroid/common/SelendroidCapabilities.java
- selendroid-server/src/main/java/io/selendroid/server/DefaultServerInstrumentation.java
- selendroid-server/src/main/java/io/selendroid/server/InstrumentationArguments.java
- selendroid-server/src/main/java/io/selendroid/server/ServerInstrumentation.java
- selendroid-server/src/main/java/io/selendroid/server/model/ExternalStorage.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
This PR changes the way in which we send extra AUT args. Instead of using the instrument command's arguments, we now write the arguments to a JSON file and push it to the device. This will free us from having to worry about the character limit on `adb` command arguments and will also allow us to send more structured args (we now support passing arbitrary `JSONObject`s)
> Move extra AUT args to a JSON file

- selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidConfiguration.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidLauncher.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidSdk.java
This PR makes it possible to specify which android sdk installation (i.e. use ANDROID_HOME or other installation), sdk version and build-tools version to use via `SelendroidConfiguration`. This is useful in environments with multiple sdk installations and cases where the latest build-tools or android-sdk are not compatible with the AUT
> Make android home, sdk and build-tools configurable

- selendroid-server/src/main/java/io/selendroid/server/model/AndroidNativeElement.java
The previous implementation of the click method would simply wait for a specific amount of time and then try to access the view's location. That approach offers no guarantee that the `getLocationOnScreen` would return a valid value.
This PR checks if the view's been laid out before calling `getLocationOnScreen`, if it hasn't been it attaches an `OnGlobalLayoutListener` to the view tree that will perform the click once the view's been properly laid out.
Note that `isLaidOut` is only available in API 19+, so we fallback to the original implementation for lower API levels
> Increase click reliability for API levels 19+

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/TelnetClient.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulator.java
As per the documentation here: https://developer.android.com/studio/run/emulator-console.html
> Each time the console displays OK, it's ready to accept commands
The old code would read a single line, which I assume was meant to parse the initial OK. Sometimes there is more text printed when you initially connect, so it is more correct to wait for the initial OK message.
> When running console commands via telnet, wait for the initial OK from the device

- selendroid-server/src/main/java/io/selendroid/server/android/internal/AndroidSystemClock.java
Using CPU didn't really make sense here and in some causes could cause timeouts for waits to be way off
> Use real time in AndroidSystemClock

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidSdk.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/android/AndroidSdkTest.java
This PR fixes the way we determine which is the latest build-tools/platform version. The previous implementation's could break if certain folders were present in an Android SDK installation, plus sorting by file name was just wrong
> Fix Android SDK logic for finding latest build-tools/platform version

- selendroid-server/src/main/java/io/selendroid/server/model/SelendroidWebDriver.java
If an application uses a WebView, Selendroid creates a WrappingSelendroidWebClient, so that WebViewClient events can be sent both to the application's own WebViewClient as well as Selendroid's WebViewClient.  (For more context, see commit a1a6a3b0943e8c6516ea49dcaa23a77e245a5b7b.)
However, if an application used a subclass of WebView, a WrappingSelendroidWebClient would not get created, because Class.getDeclaredField() did not check the fields up the class hierarchy.
The fix is to walk up the class hierarchy, looking for the field along the way.
> Proxy WebViewClient calls for a WebView subclass

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/InstrumentationProcessListener.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/InstrumentationProcessOutput.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/handler/ProxyToDeviceHandler.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/ActiveSession.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/android/InstrumentationProcessOutputTest.java
This PR adds monitoring of the instrumentation process (the `am instrument` call) . Whenever the instrumentation process died in the middle of a session, we wouldn't be able to detect it other than the Selendroid server on the device becoming unresponsive which lead to unnecessary timeouts. With these changes, we can check whenever the instrumentation process for the session has finished and fail immediately. This allows us to:
- Not need to timeout whenever the AUT is not installed
- Have proper native crash detection
- Get rid of `Server on the device became unreachable` messages
> Add monitoring of instrumentation process output

- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/DeviceStore.java
Objects.firstNotNull is deprecated since Guava 18, and is removed since guava 21
> Update DeviceStore : compatibility with Guava 21+

- selendroid-standalone/src/main/java/io/selendroid/standalone/SelendroidConfiguration.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/handler/ProxyToDeviceHandler.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
There was a race condition between detecting regular app crashes through the instrumentation process' output. Turns out that the fastest way to detect this is through the device's crash logs.  We were also checking the crash logs in `SelendroidStandaloneDriver#waitForServerStart` which is most likely going to be executed before we even create the file.
This PR:
1. Decouples regular app crash detection from instrumentation process output checks in `ProxyToDeviceHandler`
2. Replace `while (retries) { ... sleep(...) }` with `FluentWait` in `ProxyToDeviceHandler#handleRequest`
3. Remove crash log checks in `SelendroidStandaloneDriver#waitForServerStart`
4. Makes the polling interval for waiting until the server starts configurable. Default value matches `FluentWait`'s default
> Fix app crashing detection race condition

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultHardwareDevice.java
Use AbstractDevice getProp (which uses adb shell getprop)
The ddmlib IDevice getProp version is sdk dependent
> Remove DefaultHardwareDevice getProp override

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/io/ShellCommand.java
This PR ads a better API for executing shell commands asynchronously and cleans up the logging of command execution output.
Instead of logging
every
single
line
separately, we now log only the final output (no more double logging for synchronous execution), along with the command that was executed. This will make logs a lot more readable.
> Improve logging for shell command execution

- selendroid-common/src/main/java/io/selendroid/common/SelendroidCapabilities.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/AndroidDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulator.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/ActiveSession.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
Split local a remote ports used for proxying requests to the device and add a capability to enable using a random local port for forwarding
> [standalone] Split local and remote port for server

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/InstrumentationProcessOutput.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/handler/ProxyToDeviceHandler.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/SelendroidStandaloneDriver.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/android/InstrumentationProcessOutputTest.java
When introducing instrumentation output monitoring, we created a race condition between detecting app crashes through the instrumentation process output and through reading the app crashed logs.
This PR fixes that race condition and refactors the logic for mapping instrumentation output to an exception so that we can remove some duplicated logic
> Fix race condition during app crashes

- selendroid-standalone/src/main/java/io/selendroid/standalone/android/InstrumentationProcessOutput.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/handler/ProxyToDeviceHandler.java
- selendroid-standalone/src/main/java/io/selendroid/standalone/server/model/ActiveSession.java
- selendroid-standalone/src/test/java/io/selendroid/standalone/android/InstrumentationProcessOutputTest.java
We were checking the device's crash log multiple times for every request made to `ProxyToDeviceHandler` which can be very expensive, specially when running on remote emulators.
The main reason for this was that there is a race condition between the instrumentation process being terminated (which we're monitoring in a separate thread) and us writing to the crash log. However, we were supposedly getting around that race condition by waiting for the crash log to be written whenever the instrumentation process output detects a Java crash. This pull request:
- Fixes a bug in the logic for waiting for the crash log be written which made it so that we weren't really waiting
- Adds better error messages to distinguish when we can and cannot get the crash log
- Remove the crash log checks from …
> Stop polling crash logs in ProxyToDeviceHandler

- selendroid-standalone/src/main/java/io/selendroid/standalone/server/util/HttpClientUtil.java
According to the [library's docs](http://hc.apache.org/httpclient-3.x/performance.html) reusing `HttpClient` is recommended in order to improve performance
> Use only one HttpClient instance
